### ISSUE TITLE
error in dialog when creating a menu

### ISSUE THREAD

**Issue by alexraileanu** [opper/jump#11]
there's an exception when running the jumpgate:

```
Traceback (most recent call last):
  File "~/jump/venv/bin/jump", line 11, in <module>
    load_entry_point('jump', 'console_scripts', 'jump')()
  File "~/jump/jump/menu.py", line 103, in main
    Jump()
  File "~/jump/jump/menu.py", line 22, in __init__
    self.run()
  File "~/jump/jump/menu.py", line 68, in run
    code, app = self.create_menu('Choose an application', self.formatted_menu_items, 'Exit')
  File "~/jump/jump/menu.py", line 45, in create_menu
    cancel_label=cancel_label,
  File "~/jump/venv/lib/python3.7/site-packages/dialog.py", line 2911, in menu
    cmd, kwargs, strip_xdialog_newline=True)
  File "~/jump/venv/lib/python3.7/site-packages/dialog.py", line 1703, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)
  File "~/jump/venv/lib/python3.7/site-packages/dialog.py", line 1504, in _perform
    args_file)
  File "~/jump/venv/lib/python3.7/site-packages/dialog.py", line 1469, in _handle_program_exit
    child_output_rfd)
  File "~/jump/venv/lib/python3.7/site-packages/dialog.py", line 1421, in _wait_for_program_termination
    child_output.strip()))
dialog.DialogError: dialog-like terminated due to an error: the dialog-like program exited with status 3 (which was passed to it as the DIALOG_ERROR environment variable). Sometimes, the reason is simply that dialog was given a height or width parameter that is too big for the terminal in use. Its output, with leading and trailing whitespace stripped, was:

Error: Expected at least 5 tokens for --menu, have 4.
Use --help to list options.
```

could be because of the new python version? or it was somehow introduced after #7.

**Comment by alexraileanu** [comment]
turns out it wasn't an issue after all.
